# load data

In [1]:
#https://www.kaggle.com/felipekitamura/head-ct-hemorrhage

In [2]:
# 
# from glob import glob
# import os
# for i,j in enumerate(glob('../dataset/head_ct/*.png')):
#     os.rename(j, j[0:-7]+'{}.png'.format(i))

In [3]:
import pandas as pd
data=pd.read_csv('../dataset/head_ct_labels.csv')
data.columns=['img','label']
data.img='../dataset/head_ct/'+data.img.astype(str)+'.png'
data = data.sample(frac=1).reset_index(drop=True)
data.head()

                          img  label
0   ../dataset/head_ct/20.png      1
1  ../dataset/head_ct/135.png      0
2  ../dataset/head_ct/191.png      0
3   ../dataset/head_ct/35.png      1
4  ../dataset/head_ct/185.png      0

# top 5 lightest models in torchvision
1	squeezenet1_1	1235496  
2	shufflenet_v2_x0_5	1366792  
3	mnasnet0_5	2218512  
4	mobilenet_v2	3504872  
5	densenet121	7978856  `

In [4]:
import sys
sys.path.append("../src")

In [5]:
from models.squeezenet import squeezenet1_1
from models.mymodels import mymodel4
from models.shufflenet import shufflenet_v2_x0_5
from models.mnastnet import mnasnet0_5
from models.densenet import densenet121
from models.mobilenet import mobilenet
from cross_vals import kfoldcv

In [6]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)/1e6

In [7]:
print('MyNet parameters :' ,count_parameters(mymodel4()))
print('SqueezeNet parameters :', count_parameters(squeezenet1_1()))
print('ShuffleNet parameters :', count_parameters(shufflenet_v2_x0_5()))
print('MnastNet parameters :', count_parameters(mnasnet0_5()))
print('MobileNet parameters :', count_parameters(mobilenet()))
print('DenseNet parameters :', count_parameters(densenet121()))

MyNet parameters : 0.774768
SqueezeNet parameters : 0.984
ShuffleNet parameters : 0.86616
MnastNet parameters : 1.593096
MobileNet parameters : 2.879168
DenseNet parameters : 7.472384

In [8]:
epoch=20
batchsize=8
lr=0.001

# MyNet

In [9]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel4(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=1)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.856   0.846     0.844
Class 1       0.844   0.858     0.838
macro         0.852   0.852     0.840
weighted      0.866   0.846     0.844
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.908   0.902     0.894
Class 1       0.892   0.910     0.890
macro         0.900   0.906     0.894
weighted      0.916   0.894     0.896
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.858   0.848     0.842
Class 1       0.844   0.866     0.840
macro         0.850   0.856     0.842
weighted      0.870   0.846     0.844
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.860   0.888     0.864
Class 1       0.880   0.860     0.858
macro         0.870   0.874     0.862
weighted      0.886   0.866     0.866
--------------------------Accuracy Table-----------------------------------
Wall time: 11min 26s

         DT    SVM     LR    KNN
0      0.93   0.95   0.90   0.95
1      0.75   0.80   0.75   0.75
2      0.88   0.95   0.88   0.88
3      0.85   0.95   0.88   0.95
4      0.82   0.82   0.82   0.80
mean  0.846  0.894  0.846  0.866

In [10]:
# %%time
# train_cv,clf_report=kfoldcv(model=mymodel4(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=2)
# for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
#     print('------------------',clf,'----------------')
#     print(clf_report[0][clf][0])
    
# print('--------------------------Accuracy Table-----------------------------------')
# clf_report[1]

In [11]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel4(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=0)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.792   0.790     0.790
Class 1       0.796   0.804     0.796
macro         0.792   0.798     0.792
weighted      0.808   0.800     0.800
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.824   0.890     0.850
Class 1       0.880   0.826     0.844
macro         0.852   0.858     0.844
weighted      0.868   0.854     0.852
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.834   0.922     0.866
Class 1       0.906   0.824     0.858
macro         0.872   0.872     0.860
weighted      0.886   0.864     0.862
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.810   0.866     0.832
Class 1       0.858   0.810     0.830
macro         0.836   0.838     0.830
weighted      0.848   0.838     0.834
--------------------------Accuracy Table-----------------------------------
Wall time: 10min 54s

         DT    SVM     LR    KNN
0      0.88   0.95   0.97   0.93
1      0.73   0.78   0.73   0.75
2      0.73   0.78   0.85   0.78
3      0.88   0.88   0.88   0.88
4      0.80   0.88   0.90   0.85
mean  0.804  0.854  0.866  0.838

# SqueezeNet

In [12]:
%%time
train_cv,clf_report=kfoldcv(model=squeezenet1_1(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=1)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.524   0.518     0.512
Class 1       0.520   0.526     0.516
macro         0.522   0.522     0.514
weighted      0.542   0.520     0.524
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.506   0.524     0.506
Class 1       0.500   0.480     0.482
macro         0.504   0.502     0.494
weighted      0.524   0.498     0.502
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.552   0.566     0.546
Class 1       0.542   0.520     0.516
macro         0.544   0.542     0.530
weighted      0.570   0.536     0.536
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.486   0.506     0.486
Class 1       0.464   0.452     0.446
macro         0.478   0.478     0.464
weighted      0.496   0.470     0.470
--------------------------Accuracy Table-----------------------------------
Wall time: 11min 52s

        DT    SVM     LR   KNN
0     0.53   0.60   0.68  0.57
1     0.50   0.45   0.53  0.35
2     0.62   0.50   0.50  0.55
3     0.45   0.48   0.55  0.38
4     0.50   0.48   0.42  0.50
mean  0.52  0.502  0.536  0.47

In [13]:
# %%time
# train_cv,clf_report=kfoldcv(model=squeezenet1_1(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=2)
# for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
#     print('------------------',clf,'----------------')
#     print(clf_report[0][clf][0])
    
# print('--------------------------Accuracy Table-----------------------------------')
# clf_report[1]

In [14]:
%%time
train_cv,clf_report=kfoldcv(model=squeezenet1_1(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=0)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.592   0.572     0.560
Class 1       0.574   0.594     0.562
macro         0.584   0.582     0.560
weighted      0.608   0.562     0.564
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.554   0.564     0.556
Class 1       0.546   0.530     0.532
macro         0.550   0.548     0.544
weighted      0.570   0.550     0.556
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.578   0.534     0.544
Class 1       0.572   0.614     0.582
macro         0.574   0.574     0.562
weighted      0.592   0.566     0.568
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.602   0.646     0.616
Class 1       0.578   0.540     0.556
macro         0.592   0.594     0.584
weighted      0.612   0.600     0.598
--------------------------Accuracy Table-----------------------------------
Wall time: 11min 39s

         DT   SVM     LR    KNN
0      0.82  0.80   0.85   0.93
1      0.48  0.45   0.45   0.68
2      0.57  0.55   0.55   0.50
3      0.42  0.55   0.60   0.42
4      0.53  0.40   0.38   0.48
mean  0.564  0.55  0.566  0.602

# ShuffleNet

In [15]:
%%time
train_cv,clf_report=kfoldcv(model=shufflenet_v2_x0_5(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=1)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.490   0.534     0.506
Class 1       0.474   0.430     0.446
macro         0.482   0.484     0.474
weighted      0.504   0.494     0.496
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.532   0.572     0.544
Class 1       0.532   0.494     0.500
macro         0.532   0.534     0.522
weighted      0.554   0.526     0.526
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.524   0.578     0.540
Class 1       0.534   0.478     0.496
macro         0.528   0.526     0.518
weighted      0.550   0.522     0.528
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.486   0.550     0.500
Class 1       0.476   0.412     0.422
macro         0.480   0.482     0.462
weighted      0.498   0.464     0.462
--------------------------Accuracy Table-----------------------------------
Wall time: 15min 50s

         DT    SVM     LR    KNN
0      0.48   0.55   0.55   0.50
1      0.50   0.45   0.48   0.40
2      0.50   0.45   0.57   0.40
3      0.53   0.65   0.55   0.57
4      0.48   0.53   0.48   0.45
mean  0.498  0.526  0.526  0.464

In [16]:
# %%time
# train_cv,clf_report=kfoldcv(model=shufflenet_v2_x0_5(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=2)
# for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
#     print('------------------',clf,'----------------')
#     print(clf_report[0][clf][0])
    
# print('--------------------------Accuracy Table-----------------------------------')
# clf_report[1]

In [17]:
%%time
train_cv,clf_report=kfoldcv(model=shufflenet_v2_x0_5(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=0)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.476   0.458     0.456
Class 1       0.496   0.516     0.490
macro         0.484   0.484     0.470
weighted      0.508   0.476     0.476
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.538   0.562     0.540
Class 1       0.538   0.520     0.516
macro         0.538   0.542     0.526
weighted      0.560   0.530     0.534
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.546   0.576     0.550
Class 1       0.554   0.530     0.528
macro         0.550   0.552     0.538
weighted      0.574   0.542     0.544
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.534   0.478     0.494
Class 1       0.514   0.574     0.530
macro         0.524   0.524     0.510
weighted      0.548   0.516     0.516
--------------------------Accuracy Table-----------------------------------
Wall time: 15min 29s

         DT    SVM     LR    KNN
0      0.35   0.48   0.50   0.42
1      0.53   0.62   0.60   0.55
2      0.53   0.50   0.55   0.53
3      0.55   0.53   0.53   0.55
4      0.42   0.53   0.53   0.53
mean  0.476  0.532  0.542  0.516

# Mnasnet

In [18]:
%%time
train_cv,clf_report=kfoldcv(model=mnasnet0_5(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=1)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.474   0.466     0.466
Class 1       0.484   0.490     0.482
macro         0.478   0.480     0.474
weighted      0.500   0.484     0.490
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.498   0.436     0.452
Class 1       0.496   0.560     0.514
macro         0.496   0.496     0.484
weighted      0.518   0.488     0.494
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.504   0.444     0.460
Class 1       0.492   0.554     0.512
macro         0.498   0.498     0.486
weighted      0.518   0.490     0.492
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.456   0.406     0.414
Class 1       0.468   0.520     0.480
macro         0.460   0.464     0.448
weighted      0.480   0.454     0.452
--------------------------Accuracy Table-----------------------------------
Wall time: 14min 41s

         DT   SVM     LR    KNN
0      0.38  0.50   0.55   0.38
1      0.53  0.57   0.50   0.50
2      0.48  0.40   0.40   0.57
3      0.57  0.50   0.53   0.42
4      0.48  0.48   0.48   0.40
mean  0.488  0.49  0.492  0.454

In [19]:
# %%time
# train_cv,clf_report=kfoldcv(model=mnasnet0_5(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=2)
# for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
#     print('------------------',clf,'----------------')
#     print(clf_report[0][clf][0])
    
# print('--------------------------Accuracy Table-----------------------------------')
# clf_report[1]

In [20]:
%%time
train_cv,clf_report=kfoldcv(model=mnasnet0_5(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=0)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.526   0.500     0.462
Class 1       0.474   0.468     0.446
macro         0.502   0.482     0.450
weighted      0.522   0.478     0.460
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.516   0.524     0.504
Class 1       0.516   0.502     0.492
macro         0.518   0.514     0.498
weighted      0.536   0.500     0.502
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.480   0.484     0.466
Class 1       0.488   0.482     0.470
macro         0.484   0.484     0.468
weighted      0.502   0.472     0.470
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.560   0.472     0.496
Class 1       0.554   0.640     0.580
macro         0.556   0.554     0.540
weighted      0.576   0.550     0.546
--------------------------Accuracy Table-----------------------------------
Wall time: 14min 25s

        DT   SVM     LR   KNN
0     0.55  0.65   0.60  0.62
1     0.50  0.57   0.60  0.65
2     0.45  0.45   0.40  0.53
3     0.42  0.45   0.38  0.50
4     0.48  0.38   0.38  0.45
mean  0.48   0.5  0.472  0.55

# MobileNet

In [21]:
%%time
train_cv,clf_report=kfoldcv(model=mobilenet(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=1)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.572   0.564     0.552
Class 1       0.562   0.574     0.550
macro         0.570   0.570     0.548
weighted      0.590   0.552     0.554
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.544   0.448     0.474
Class 1       0.512   0.598     0.538
macro         0.528   0.524     0.504
weighted      0.550   0.508     0.510
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.560   0.514     0.520
Class 1       0.532   0.574     0.538
macro         0.548   0.542     0.526
weighted      0.568   0.530     0.530
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.538   0.666     0.572
Class 1       0.576   0.436     0.460
macro         0.558   0.548     0.516
weighted      0.580   0.524     0.514
--------------------------Accuracy Table-----------------------------------
Wall time: 15min 38s

         DT    SVM    LR    KNN
0      0.53   0.57  0.62   0.50
1      0.57   0.57  0.60   0.48
2      0.42   0.28  0.28   0.50
3      0.62   0.57  0.62   0.70
4      0.62   0.55  0.53   0.45
mean  0.552  0.508  0.53  0.526

In [22]:
# %%time
# train_cv,clf_report=kfoldcv(model=mobilenet(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=2)
# for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
#     print('------------------',clf,'----------------')
#     print(clf_report[0][clf][0])
    
# print('--------------------------Accuracy Table-----------------------------------')
# clf_report[1]

In [23]:
%%time
train_cv,clf_report=kfoldcv(model=mobilenet(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=0)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.482   0.508     0.492
Class 1       0.462   0.430     0.444
macro         0.472   0.470     0.470
weighted      0.496   0.486     0.488
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.474   0.498     0.476
Class 1       0.464   0.448     0.446
macro         0.468   0.474     0.460
weighted      0.490   0.470     0.470
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.494   0.466     0.470
Class 1       0.486   0.522     0.494
macro         0.490   0.494     0.484
weighted      0.510   0.494     0.492
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.516   0.650     0.564
Class 1       0.514   0.390     0.430
macro         0.516   0.520     0.496
weighted      0.538   0.508     0.504
--------------------------Accuracy Table-----------------------------------
Wall time: 15min 19s

         DT    SVM     LR   KNN
0      0.60   0.38   0.48  0.42
1      0.45   0.48   0.50  0.53
2      0.53   0.50   0.53  0.55
3      0.50   0.45   0.42  0.48
4      0.35   0.55   0.55  0.57
mean  0.486  0.472  0.496  0.51

# DenseNet121

In [24]:
%%time
train_cv,clf_report=kfoldcv(model=densenet121(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=1)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

C:\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py:688: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
C:\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py:688: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.864   0.844     0.854
Class 1       0.850   0.874     0.856
macro         0.858   0.862     0.852
weighted      0.870   0.862     0.858
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.890   0.832     0.858
Class 1       0.844   0.900     0.870
macro         0.868   0.868     0.862
weighted      0.876   0.870     0.868
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.868   0.856     0.860
Class 1       0.862   0.884     0.870
macro         0.868   0.870     0.862
weighted      0.878   0.872     0.868
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.856   0.824     0.834
Class 1       0.830   0.866     0.838
macro         0.844   0.842     0.836
weighted      0.856   0.840     0.838
--------------------------Accuracy Table-----------------------------------
Wall time: 26min 11s

         DT   SVM     LR   KNN
0      0.93  0.97   0.97  0.82
1      0.90  0.90   0.88  0.88
2      0.75  0.78   0.78  0.80
3      0.88  0.85   0.88  0.88
4      0.85  0.85   0.85  0.82
mean  0.862  0.87  0.872  0.84

In [25]:
# %%time
# train_cv,clf_report=kfoldcv(model=densenet121(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=2)
# for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
#     print('------------------',clf,'----------------')
#     print(clf_report[0][clf][0])
    
# print('--------------------------Accuracy Table-----------------------------------')
# clf_report[1]

In [26]:
%%time
train_cv,clf_report=kfoldcv(model=densenet121(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=0)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.776   0.742     0.756
Class 1       0.748   0.792     0.762
macro         0.762   0.764     0.758
weighted      0.778   0.764     0.766
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.844   0.842     0.836
Class 1       0.826   0.844     0.828
macro         0.834   0.840     0.830
weighted      0.854   0.834     0.834
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.830   0.854     0.832
Class 1       0.828   0.812     0.810
macro         0.830   0.828     0.818
weighted      0.848   0.824     0.826
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.768   0.826     0.794
Class 1       0.810   0.768     0.786
macro         0.790   0.798     0.790
weighted      0.804   0.796     0.794
--------------------------Accuracy Table-----------------------------------
Wall time: 25min 20s

         DT    SVM     LR    KNN
0      0.97   0.97   0.97   0.93
1      0.80   0.85   0.82   0.73
2      0.75   0.85   0.88   0.80
3      0.55   0.73   0.70   0.68
4      0.75   0.78   0.75   0.85
mean  0.764  0.836  0.824  0.798