# load data

In [1]:
from glob import glob
import os
images=[]
labels=[]
for folder in os.listdir('../dataset/wrist_xray'):
    for pic in glob('../dataset/wrist_xray/{}/*.jpg'.format(folder)):
        images.append(pic)
        labels.append(folder)

In [2]:
import pandas as pd
data=pd.DataFrame(zip(images,labels),columns=['img','label'])
data.label=data.label.map({'Fracture':0,'Normal':1})
data = data.sample(frac=1).reset_index(drop=True)
data.head()

                                                 img  label
0  ../dataset/wrist_xray/Fracture\90 Male (A View...      0
1   ../dataset/wrist_xray/Fracture\40 F (A View).jpg      0
2  ../dataset/wrist_xray/Fracture\48 Male (A View...      0
3  ../dataset/wrist_xray/Fracture\5 Male (A View)...      0
4  ../dataset/wrist_xray/Fracture\67 Male (A View...      0

# top 5 lightest models in torchvision
1	squeezenet1_1	1235496  
2	shufflenet_v2_x0_5	1366792  
3	mnasnet0_5	2218512  
4	mobilenet_v2	3504872  
5	densenet121	7978856  `

In [3]:
import sys
sys.path.append("../src")

In [4]:
from models.squeezenet import squeezenet1_1
from models.mymodels import mymodel1,mymodel2,mymodel3,mymodel4
from models.shufflenet import shufflenet_v2_x0_5
from models.mnastnet import mnasnet0_5
from models.densenet import densenet121
from models.mobilenet import mobilenet
from cross_vals import kfoldcv

In [5]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)/1e6

d:\tutorials\automl\venv\lib\site-packages\ipykernel\ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [6]:
print('MyNet1 parameters :' ,count_parameters(mymodel1()))
print('MyNet2 parameters :', count_parameters(mymodel2()))
print('MyNet3 parameters :', count_parameters(mymodel3()))
print('MyNet4 parameters :', count_parameters(mymodel4()))

MyNet1 parameters : 1.158232
MyNet2 parameters : 1.158232
MyNet3 parameters : 1.157848
MyNet4 parameters : 1.157848

In [7]:
epoch=32
batchsize=8
lr=0.001

dim='3D' or '2D' for 3D images and 2D iamges
skip_tuning=False, no grid search applied for hyper-parameter tuning, 
aug=1-> pytorch augmentation
aug=0-> no augmentation
aug=2-> albumentation augmentation
aug=3-> rand augmentation

# MyNet

In [8]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel1(),epochs=epoch,batchsize=batchsize,data=data,\
                            lr=lr,skip_tuning=False,aug=1,dim='2D',pca=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors','autoML']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.888   0.864     0.876
Class 1       0.812   0.830     0.822
macro         0.848   0.846     0.848
weighted      0.854   0.854     0.854
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.904   0.866     0.884
Class 1       0.818   0.858     0.838
macro         0.862   0.860     0.862
weighted      0.866   0.866     0.864
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.910   0.858     0.886
Class 1       0.808   0.870     0.838
macro         0.860   0.864     0.860
weighted      0.868   0.866     0.866
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.894   0.848     0.868
Class 1       0.800   0.846     0.820
macro         0.846   0.846     0.844
weighted      0.856   0.850     0.850
------------------ autoML ----------------
          precision  recall  f1-score
Class 0       0.922   0.936     0.928
Class 1       0.906   0.870     0.884
macro         0.912   0.902     0.906
weighted      0.912   0.912     0.910
--------------------------Accuracy Table-----------------------------------
Wall time: 16min 19s

         DT    SVM     LR   KNN     ML
0      0.79   0.87   0.85  0.79   0.92
1      0.87   0.85   0.85  0.85   0.90
2      0.92   0.95   0.97  0.95   1.00
3      0.74   0.71   0.71  0.74   0.79
4      0.95   0.95   0.95  0.92   0.95
mean  0.854  0.866  0.866  0.85  0.912

In [9]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel2(),epochs=epoch,batchsize=batchsize,data=data,\
                            lr=lr,skip_tuning=False,aug=1,dim='2D',pca=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors','autoML']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.872   0.824     0.844
Class 1       0.782   0.830     0.804
macro         0.830   0.828     0.822
weighted      0.832   0.830     0.828
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.858   0.874     0.866
Class 1       0.828   0.804     0.816
macro         0.840   0.836     0.838
weighted      0.844   0.844     0.844
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.854   0.884     0.868
Class 1       0.834   0.794     0.814
macro         0.840   0.836     0.838
weighted      0.844   0.844     0.844
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.890   0.874     0.882
Class 1       0.834   0.854     0.842
macro         0.864   0.864     0.862
weighted      0.866   0.866     0.866
------------------ autoML ----------------
          precision  recall  f1-score
Class 0       0.908   0.884     0.894
Class 1       0.846   0.880     0.862
macro         0.878   0.880     0.878
weighted      0.880   0.878     0.880
--------------------------Accuracy Table-----------------------------------
Wall time: 15min 36s

        DT    SVM     LR    KNN     ML
0     0.85   0.85   0.85   0.85   0.87
1     0.92   0.90   0.90   0.92   0.92
2     0.72   0.74   0.74   0.82   0.79
3     0.82   0.84   0.84   0.87   0.89
4     0.84   0.89   0.89   0.87   0.92
mean  0.83  0.844  0.844  0.866  0.878

In [10]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel3(),epochs=epoch,batchsize=batchsize,data=data,\
                            lr=lr,skip_tuning=False,aug=1,dim='2D',pca=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors','autoML']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.896   0.902     0.896
Class 1       0.870   0.850     0.854
macro         0.882   0.878     0.876
weighted      0.888   0.878     0.880
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.952   0.892     0.920
Class 1       0.868   0.938     0.898
macro         0.910   0.916     0.910
weighted      0.916   0.910     0.910
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.918   0.912     0.914
Class 1       0.880   0.888     0.882
macro         0.900   0.900     0.900
weighted      0.904   0.902     0.902
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.944   0.910     0.924
Class 1       0.886   0.926     0.904
macro         0.914   0.918     0.916
weighted      0.920   0.916     0.916
------------------ autoML ----------------
          precision  recall  f1-score
Class 0       0.954   0.926     0.940
Class 1       0.908   0.940     0.924
macro         0.932   0.934     0.930
weighted      0.936   0.932     0.932
--------------------------Accuracy Table-----------------------------------
Wall time: 15min 12s

         DT   SVM     LR    KNN     ML
0      0.87  0.95   0.95   0.92   0.97
1      0.92  0.92   0.90   0.92   0.97
2      0.87  0.87   0.87   0.90   0.90
3      0.76  0.84   0.84   0.87   0.87
4      0.97  0.97   0.95   0.97   0.95
mean  0.878  0.91  0.902  0.916  0.932

In [11]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel4(),epochs=epoch,batchsize=batchsize,data=data,\
                            lr=lr,skip_tuning=False,aug=1,dim='2D',pca=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors','autoML']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.872   0.856     0.862
Class 1       0.812   0.834     0.820
macro         0.844   0.844     0.840
weighted      0.850   0.844     0.844
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.860   0.874     0.864
Class 1       0.826   0.806     0.814
macro         0.842   0.840     0.840
weighted      0.846   0.844     0.844
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.860   0.874     0.864
Class 1       0.826   0.806     0.814
macro         0.842   0.840     0.840
weighted      0.846   0.844     0.844
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.858   0.866     0.858
Class 1       0.818   0.808     0.812
macro         0.838   0.836     0.836
weighted      0.842   0.840     0.840
------------------ autoML ----------------
          precision  recall  f1-score
Class 0       0.882   0.910     0.894
Class 1       0.876   0.830     0.846
macro         0.878   0.868     0.870
weighted      0.880   0.874     0.874
--------------------------Accuracy Table-----------------------------------
Wall time: 15min 36s

         DT    SVM     LR   KNN     ML
0      0.95   0.92   0.92  0.90   0.92
1      0.87   0.87   0.87  0.87   0.90
2      0.79   0.77   0.77  0.74   0.82
3      0.79   0.79   0.79  0.82   0.84
4      0.82   0.87   0.87  0.87   0.89
mean  0.844  0.844  0.844  0.84  0.874