# load data

In [1]:
from glob import glob
import os
images=[]
labels=[]
for folder in os.listdir('../dataset/wrist_xray'):
    for pic in glob('../dataset/wrist_xray/{}/*.jpg'.format(folder)):
        images.append(pic)
        labels.append(folder)

In [2]:
import pandas as pd
data=pd.DataFrame(zip(images,labels),columns=['img','label'])
data.label=data.label.map({'Fracture':0,'Normal':1})
data = data.sample(frac=1).reset_index(drop=True)
data.head()

                                                 img  label
0                ../dataset/wrist_xray/Normal\77.jpg      1
1  ../dataset/wrist_xray/Fracture\92 Male (A View...      0
2  ../dataset/wrist_xray/Fracture\6 Female (L Vie...      0
3                ../dataset/wrist_xray/Normal\35.jpg      1
4                ../dataset/wrist_xray/Normal\80.jpg      1

# top 5 lightest models in torchvision
1	squeezenet1_1	1235496  
2	shufflenet_v2_x0_5	1366792  
3	mnasnet0_5	2218512  
4	mobilenet_v2	3504872  
5	densenet121	7978856  `

In [3]:
import sys
sys.path.append("../src")

In [4]:
from models.squeezenet import squeezenet1_1
from models.mymodels import mymodel1,mymodel2,mymodel3,mymodel4
from models.shufflenet import shufflenet_v2_x0_5
from models.mnastnet import mnasnet0_5
from models.densenet import densenet121
from models.mobilenet import mobilenet
from cross_vals import kfoldcv

In [5]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)/1e6

d:\tutorials\automl\venv\lib\site-packages\ipykernel\ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [6]:
print('MyNet1 parameters :' ,count_parameters(mymodel1()))
print('MyNet2 parameters :', count_parameters(mymodel2()))
print('MyNet3 parameters :', count_parameters(mymodel3()))
print('MyNet4 parameters :', count_parameters(mymodel4()))

MyNet1 parameters : 1.158232
MyNet2 parameters : 1.158232
MyNet3 parameters : 1.157848
MyNet4 parameters : 1.157848

In [7]:
epoch=32
batchsize=8
lr=0.001

dim='3D' or '2D' for 3D images and 2D iamges
skip_tuning=False, no grid search applied for hyper-parameter tuning, 
aug=1-> pytorch augmentation
aug=0-> no augmentation
aug=2-> albumentation augmentation
aug=3-> rand augmentation

# MyNet

In [8]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel1(),epochs=epoch,batchsize=batchsize,data=data,\
                            lr=lr,skip_tuning=False,aug=0,dim='2D',pca=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors','autoML']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.656   0.624     0.626
Class 1       0.520   0.550     0.516
macro         0.592   0.588     0.568
weighted      0.608   0.586     0.578
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.738   0.756     0.742
Class 1       0.688   0.638     0.652
macro         0.712   0.696     0.698
weighted      0.718   0.716     0.712
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.740   0.766     0.748
Class 1       0.684   0.628     0.638
macro         0.712   0.696     0.694
weighted      0.720   0.714     0.708
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.740   0.738     0.728
Class 1       0.674   0.652     0.648
macro         0.706   0.694     0.688
weighted      0.718   0.706     0.702
------------------ autoML ----------------
          precision  recall  f1-score
Class 0       0.816   0.796     0.792
Class 1       0.768   0.716     0.724
macro         0.792   0.754     0.760
weighted      0.794   0.778     0.770
--------------------------Accuracy Table-----------------------------------
Wall time: 16min 6s

         DT    SVM     LR    KNN     ML
0      0.67   0.77   0.69   0.69   0.85
1      0.59   0.62   0.67   0.62   0.77
2      0.54   0.77   0.74   0.85   0.77
3      0.63   0.74   0.79   0.79   0.79
4      0.50   0.68   0.68   0.58   0.71
mean  0.586  0.716  0.714  0.706  0.778

In [9]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel2(),epochs=epoch,batchsize=batchsize,data=data,\
                            lr=lr,skip_tuning=False,aug=0,dim='2D',pca=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors','autoML']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.678   0.802     0.728
Class 1       0.662   0.490     0.550
macro         0.668   0.644     0.638
weighted      0.686   0.664     0.654
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.786   0.800     0.790
Class 1       0.714   0.710     0.704
macro         0.750   0.754     0.746
weighted      0.768   0.756     0.758
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.780   0.748     0.758
Class 1       0.668   0.708     0.676
macro         0.722   0.728     0.718
weighted      0.744   0.726     0.726
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.710   0.770     0.732
Class 1       0.638   0.564     0.584
macro         0.676   0.666     0.660
weighted      0.694   0.678     0.674
------------------ autoML ----------------
          precision  recall  f1-score
Class 0        0.78   0.860     0.810
Class 1        0.78   0.656     0.694
macro          0.78   0.758     0.752
weighted       0.79   0.770     0.768
--------------------------Accuracy Table-----------------------------------
Wall time: 15min 40s

         DT    SVM     LR    KNN    ML
0      0.62   0.85   0.82   0.77  0.79
1      0.67   0.74   0.77   0.64  0.77
2      0.59   0.69   0.69   0.64  0.74
3      0.76   0.71   0.61   0.68  0.76
4      0.68   0.79   0.74   0.66  0.79
mean  0.664  0.756  0.726  0.678  0.77

In [10]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel3(),epochs=epoch,batchsize=batchsize,data=data,\
                            lr=lr,skip_tuning=False,aug=0,dim='2D',pca=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors','autoML']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.642   0.686     0.656
Class 1       0.542   0.490     0.504
macro         0.592   0.586     0.580
weighted      0.612   0.600     0.598
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.764   0.784     0.772
Class 1       0.704   0.682     0.684
macro         0.734   0.736     0.728
weighted      0.748   0.734     0.736
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.748   0.788     0.764
Class 1       0.698   0.654     0.668
macro         0.722   0.718     0.714
weighted      0.736   0.724     0.724
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.682   0.730     0.700
Class 1       0.588   0.538     0.558
macro         0.636   0.632     0.628
weighted      0.652   0.648     0.646
------------------ autoML ----------------
          precision  recall  f1-score
Class 0       0.780   0.870     0.820
Class 1       0.800   0.674     0.726
macro         0.790   0.774     0.772
weighted      0.794   0.786     0.784
--------------------------Accuracy Table-----------------------------------
Wall time: 15min 21s

        DT    SVM     LR    KNN     ML
0     0.56   0.69   0.77   0.67   0.79
1     0.64   0.79   0.82   0.72   0.85
2     0.67   0.82   0.82   0.67   0.82
3     0.58   0.71   0.71   0.63   0.79
4     0.55   0.66   0.50   0.55   0.68
mean   0.6  0.734  0.724  0.648  0.786

In [11]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel4(),epochs=epoch,batchsize=batchsize,data=data,\
                            lr=lr,skip_tuning=False,aug=0,dim='2D',pca=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors','autoML']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.636   0.646     0.636
Class 1       0.506   0.500     0.492
macro         0.570   0.574     0.564
weighted      0.592   0.582     0.576
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.740   0.744     0.736
Class 1       0.650   0.660     0.648
macro         0.694   0.700     0.694
weighted      0.710   0.698     0.702
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.764   0.852     0.800
Class 1       0.754   0.648     0.688
macro         0.758   0.748     0.746
weighted      0.770   0.762     0.756
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.656   0.694     0.666
Class 1       0.558   0.512     0.518
macro         0.606   0.604     0.596
weighted      0.620   0.616     0.610
------------------ autoML ----------------
          precision  recall  f1-score
Class 0       0.744   0.824     0.776
Class 1       0.720   0.622     0.658
macro         0.732   0.724     0.718
weighted      0.742   0.730     0.726
--------------------------Accuracy Table-----------------------------------
Wall time: 16min 12s

         DT    SVM     LR    KNN    ML
0      0.56   0.74   0.69   0.64  0.72
1      0.49   0.64   0.82   0.56  0.69
2      0.62   0.74   0.87   0.64  0.77
3      0.71   0.82   0.82   0.74  0.89
4      0.53   0.55   0.61   0.50  0.58
mean  0.582  0.698  0.762  0.616  0.73