# load data

In [1]:
from glob import glob
import os
images=[]
labels=[]
for folder in os.listdir('../dataset'):
    for pic in glob('../dataset/{}/*.jpg'.format(folder)):
        images.append(pic)
        labels.append(folder)

In [2]:
import pandas as pd
data=pd.DataFrame(zip(images,labels),columns=['img','label'])
data.label=data.label.map({'Fracture':0,'Normal':1})
data = data.sample(frac=1).reset_index(drop=True)
data.head()

                                        img  label
0                  ../dataset/Normal\23.jpg      1
1  ../dataset/Fracture\81 Male (A View).jpg      0
2  ../dataset/Fracture\48 Male (L View).jpg      0
3                  ../dataset/Normal\58.jpg      1
4                  ../dataset/Normal\55.jpg      1

# top 5 lightest models in torchvision
1	squeezenet1_1	1235496  
2	shufflenet_v2_x0_5	1366792  
3	mnasnet0_5	2218512  
4	mobilenet_v2	3504872  
5	densenet121	7978856  `

In [3]:
from models.squeezenet import squeezenet1_1
from models.mymodels import mymodel4
from models.shufflenet import shufflenet_v2_x0_5
from models.mnastnet import mnasnet0_5
from models.densenet import densenet121
from models.mobilenet import mobilenet
from cross_vals import kfoldcv

In [4]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)/1e6

In [5]:
print('MyNet parameters :' ,count_parameters(mymodel4()))
print('SqueezeNet parameters :', count_parameters(squeezenet1_1()))
print('ShuffleNet parameters :', count_parameters(shufflenet_v2_x0_5()))
print('MnastNet parameters :', count_parameters(mnasnet0_5()))
print('MobileNet parameters :', count_parameters(mobilenet()))
print('DenseNet parameters :', count_parameters(densenet121()))

MyNet parameters : 0.774768
SqueezeNet parameters : 0.984
ShuffleNet parameters : 0.86616
MnastNet parameters : 1.593096
MobileNet parameters : 2.879168
DenseNet parameters : 7.472384

In [6]:
import torch
import numpy as np

In [7]:
epoch=25
batchsize=8
lr=0.001

# MyNet

In [8]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel4(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=True)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Fracture      0.910   0.832     0.866
Normal        0.796   0.888     0.838
macro         0.856   0.860     0.854
weighted      0.868   0.856     0.856
------------------ SVM ----------------
          precision  recall  f1-score
Fracture      0.920   0.850     0.880
Normal        0.820   0.902     0.854
macro         0.870   0.876     0.868
weighted      0.882   0.872     0.874
------------------ logistic regression ----------------
          precision  recall  f1-score
Fracture      0.912   0.850     0.876
Normal        0.820   0.890     0.848
macro         0.864   0.870     0.862
weighted      0.876   0.866     0.868
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Fracture      0.920   0.838     0.874
Normal        0.814   0.904     0.852
macro         0.866   0.872     0.862
weighted      0.876   0.864     0.866
--------------------------Accuracy Table-----------------------------------
Wall time: 10min 3s

         DT    SVM     LR    KNN
0      0.87   0.90   0.87   0.87
1      0.85   0.85   0.85   0.87
2      0.90   0.90   0.90   0.87
3      0.71   0.76   0.76   0.76
4      0.95   0.95   0.95   0.95
mean  0.856  0.872  0.866  0.864

In [9]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel4(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Fracture      0.690   0.710     0.692
Normal        0.568   0.544     0.546
macro         0.630   0.626     0.618
weighted      0.646   0.644     0.636
------------------ SVM ----------------
          precision  recall  f1-score
Fracture      0.806   0.764     0.784
Normal        0.706   0.758     0.728
macro         0.758   0.760     0.756
weighted      0.772   0.760     0.762
------------------ logistic regression ----------------
          precision  recall  f1-score
Fracture      0.818   0.822     0.816
Normal        0.766   0.752     0.756
macro         0.792   0.790     0.782
weighted      0.802   0.792     0.792
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Fracture      0.682   0.692     0.678
Normal        0.608   0.560     0.562
macro         0.644   0.628     0.620
weighted      0.658   0.638     0.630
--------------------------Accuracy Table-----------------------------------
Wall time: 8min 37s

         DT   SVM     LR    KNN
0      0.67  0.79   0.85   0.72
1      0.59  0.74   0.72   0.59
2      0.59  0.74   0.79   0.59
3      0.74  0.74   0.76   0.58
4      0.63  0.79   0.84   0.71
mean  0.644  0.76  0.792  0.638

# SqueezeNet

In [10]:
%%time
train_cv,clf_report=kfoldcv(model=squeezenet1_1(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=True)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Fracture      0.670   0.696     0.678
Normal        0.578   0.538     0.552
macro         0.624   0.616     0.616
weighted      0.634   0.636     0.634
------------------ SVM ----------------
          precision  recall  f1-score
Fracture      0.642   0.680     0.660
Normal        0.524   0.488     0.502
macro         0.584   0.582     0.580
weighted      0.600   0.602     0.598
------------------ logistic regression ----------------
          precision  recall  f1-score
Fracture      0.668   0.708     0.686
Normal        0.564   0.520     0.542
macro         0.616   0.612     0.614
weighted      0.632   0.632     0.630
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Fracture      0.664   0.718     0.690
Normal        0.578   0.510     0.538
macro         0.620   0.612     0.614
weighted      0.634   0.640     0.634
--------------------------Accuracy Table-----------------------------------
Wall time: 9min 36s

         DT    SVM     LR   KNN
0      0.82   0.77   0.82  0.85
1      0.62   0.56   0.59  0.62
2      0.56   0.49   0.54  0.44
3      0.55   0.61   0.68  0.66
4      0.63   0.58   0.53  0.63
mean  0.636  0.602  0.632  0.64

In [11]:
%%time
train_cv,clf_report=kfoldcv(model=squeezenet1_1(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Fracture      0.650   0.648     0.640
Normal        0.504   0.510     0.496
macro         0.578   0.578     0.568
weighted      0.594   0.590     0.584
------------------ SVM ----------------
          precision  recall  f1-score
Fracture      0.658   0.740     0.686
Normal        0.596   0.474     0.502
macro         0.624   0.608     0.594
weighted      0.644   0.618     0.608
------------------ logistic regression ----------------
          precision  recall  f1-score
Fracture      0.658   0.726     0.682
Normal        0.546   0.472     0.488
macro         0.602   0.602     0.588
weighted      0.620   0.610     0.600
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Fracture      0.622   0.606     0.608
Normal        0.480   0.502     0.486
macro         0.552   0.554     0.546
weighted      0.570   0.560     0.560
--------------------------Accuracy Table-----------------------------------
Wall time: 8min 48s

        DT    SVM    LR   KNN
0     0.74   0.77  0.79  0.72
1     0.54   0.51  0.51  0.49
2     0.51   0.59  0.51  0.46
3     0.63   0.61  0.63  0.58
4     0.53   0.61  0.61  0.55
mean  0.59  0.618  0.61  0.56

# ShuffleNet

In [12]:
%%time
train_cv,clf_report=kfoldcv(model=shufflenet_v2_x0_5(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=True)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Fracture      0.612   0.656     0.616
Normal        0.490   0.436     0.432
macro         0.552   0.546     0.524
weighted      0.570   0.550     0.534
------------------ SVM ----------------
          precision  recall  f1-score
Fracture      0.656   0.762     0.694
Normal        0.612   0.454     0.496
macro         0.634   0.608     0.594
weighted      0.646   0.622     0.608
------------------ logistic regression ----------------
          precision  recall  f1-score
Fracture      0.664   0.696     0.670
Normal        0.538   0.506     0.506
macro         0.600   0.602     0.588
weighted      0.618   0.606     0.598
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Fracture      0.644   0.764     0.690
Normal        0.556   0.424     0.460
macro         0.602   0.594     0.574
weighted      0.614   0.610     0.588
--------------------------Accuracy Table-----------------------------------
Wall time: 13min 26s

        DT    SVM     LR   KNN
0     0.49   0.72   0.69  0.62
1     0.49   0.56   0.56  0.67
2     0.51   0.54   0.46  0.49
3     0.58   0.71   0.71  0.61
4     0.68   0.58   0.61  0.66
mean  0.55  0.622  0.606  0.61

In [13]:
%%time
train_cv,clf_report=kfoldcv(model=shufflenet_v2_x0_5(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Fracture      0.598   0.576     0.582
Normal        0.450   0.474     0.454
macro         0.526   0.524     0.516
weighted      0.546   0.530     0.530
------------------ SVM ----------------
          precision  recall  f1-score
Fracture      0.544   0.548     0.540
Normal        0.382   0.376     0.370
macro         0.464   0.462     0.454
weighted      0.484   0.472     0.470
------------------ logistic regression ----------------
          precision  recall  f1-score
Fracture      0.546   0.550     0.542
Normal        0.390   0.386     0.382
macro         0.468   0.466     0.460
weighted      0.490   0.474     0.476
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Fracture      0.572   0.556     0.560
Normal        0.400   0.420     0.402
macro         0.482   0.488     0.480
weighted      0.506   0.496     0.494
--------------------------Accuracy Table-----------------------------------
Wall time: 12min 41s

        DT    SVM     LR    KNN
0     0.62   0.49   0.51   0.51
1     0.41   0.44   0.44   0.56
2     0.59   0.54   0.56   0.41
3     0.53   0.39   0.39   0.53
4     0.50   0.50   0.47   0.47
mean  0.53  0.472  0.474  0.496

# Mnasnet

In [14]:
%%time
train_cv,clf_report=kfoldcv(model=mnasnet0_5(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=True)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Fracture      0.800   0.676     0.730
Normal        0.652   0.784     0.710
macro         0.724   0.732     0.720
weighted      0.738   0.724     0.724
------------------ SVM ----------------
          precision  recall  f1-score
Fracture      0.828   0.734     0.774
Normal        0.626   0.742     0.672
macro         0.728   0.738     0.722
weighted      0.744   0.736     0.732
------------------ logistic regression ----------------
          precision  recall  f1-score
Fracture      0.828   0.734     0.774
Normal        0.626   0.742     0.672
macro         0.728   0.738     0.722
weighted      0.744   0.736     0.732
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Fracture      0.836   0.706     0.764
Normal        0.634   0.778     0.696
macro         0.738   0.744     0.730
weighted      0.754   0.736     0.736
--------------------------Accuracy Table-----------------------------------
Wall time: 11min 58s

         DT    SVM     LR    KNN
0      0.38   0.44   0.44   0.44
1      0.82   0.79   0.79   0.79
2      0.92   0.92   0.92   0.92
3      0.74   0.74   0.74   0.71
4      0.76   0.79   0.79   0.82
mean  0.724  0.736  0.736  0.736

In [15]:
%%time
train_cv,clf_report=kfoldcv(model=mnasnet0_5(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Fracture      0.564   0.628     0.586
Normal        0.376   0.332     0.334
macro         0.468   0.480     0.458
weighted      0.488   0.494     0.472
------------------ SVM ----------------
          precision  recall  f1-score
Fracture      0.658   0.756     0.698
Normal        0.584   0.468     0.516
macro         0.622   0.608     0.608
weighted      0.632   0.632     0.624
------------------ logistic regression ----------------
          precision  recall  f1-score
Fracture      0.672   0.736     0.700
Normal        0.604   0.522     0.558
macro         0.638   0.626     0.628
weighted      0.646   0.644     0.638
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Fracture      0.594   0.582     0.578
Normal        0.388   0.422     0.396
macro         0.494   0.502     0.490
weighted      0.516   0.518     0.508
--------------------------Accuracy Table-----------------------------------
Wall time: 13min 50s

         DT    SVM     LR    KNN
0      0.41   0.69   0.62   0.44
1      0.54   0.67   0.67   0.64
2      0.44   0.51   0.51   0.49
3      0.58   0.63   0.63   0.55
4      0.50   0.66   0.79   0.47
mean  0.494  0.632  0.644  0.518

# MobileNet

In [16]:
%%time
train_cv,clf_report=kfoldcv(model=mobilenet(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=True)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Fracture      0.706   0.732     0.710
Normal        0.652   0.594     0.604
macro         0.680   0.662     0.656
weighted      0.682   0.668     0.666
------------------ SVM ----------------
          precision  recall  f1-score
Fracture      0.704   0.756     0.716
Normal        0.632   0.558     0.574
macro         0.670   0.656     0.644
weighted      0.670   0.662     0.654
------------------ logistic regression ----------------
          precision  recall  f1-score
Fracture      0.704   0.726     0.708
Normal        0.650   0.602     0.612
macro         0.680   0.664     0.658
weighted      0.682   0.670     0.666
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Fracture      0.738   0.784     0.754
Normal        0.700   0.614     0.636
macro         0.720   0.700     0.694
weighted      0.726   0.708     0.702
--------------------------Accuracy Table-----------------------------------
Wall time: 21min 19s

         DT    SVM    LR    KNN
0      0.38   0.56  0.51   0.56
1      0.90   0.90  0.90   0.87
2      0.54   0.33  0.36   0.56
3      0.68   0.68  0.74   0.71
4      0.84   0.84  0.84   0.84
mean  0.668  0.662  0.67  0.708

In [17]:
%%time
train_cv,clf_report=kfoldcv(model=mobilenet(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Fracture      0.572   0.554     0.552
Normal        0.424   0.446     0.420
macro         0.498   0.498     0.486
weighted      0.520   0.502     0.496
------------------ SVM ----------------
          precision  recall  f1-score
Fracture      0.594   0.682     0.636
Normal        0.486   0.382     0.422
macro         0.540   0.534     0.530
weighted      0.556   0.556     0.546
------------------ logistic regression ----------------
          precision  recall  f1-score
Fracture      0.574   0.630     0.596
Normal        0.414   0.364     0.380
macro         0.492   0.496     0.490
weighted      0.510   0.512     0.506
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Fracture      0.628   0.648     0.628
Normal        0.484   0.466     0.462
macro         0.556   0.556     0.544
weighted      0.576   0.568     0.562
--------------------------Accuracy Table-----------------------------------
Wall time: 19min 48s

         DT    SVM     LR    KNN
0      0.46   0.62   0.56   0.56
1      0.54   0.49   0.46   0.56
2      0.49   0.46   0.41   0.67
3      0.47   0.55   0.45   0.50
4      0.55   0.66   0.68   0.55
mean  0.502  0.556  0.512  0.568

# DenseNet121

In [20]:
%%time
train_cv,clf_report=kfoldcv(model=densenet121(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=True)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Fracture      0.724   0.626     0.668
Normal        0.528   0.620     0.562
macro         0.626   0.624     0.614
weighted      0.644   0.632     0.628
------------------ SVM ----------------
          precision  recall  f1-score
Fracture      0.786   0.690     0.732
Normal        0.632   0.732     0.676
macro         0.710   0.712     0.702
weighted      0.726   0.712     0.712
------------------ logistic regression ----------------
          precision  recall  f1-score
Fracture      0.784   0.796     0.788
Normal        0.698   0.676     0.686
macro         0.742   0.738     0.738
weighted      0.752   0.750     0.750
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Fracture      0.716   0.630     0.664
Normal        0.564   0.650     0.596
macro         0.642   0.640     0.630
weighted      0.658   0.636     0.636
--------------------------Accuracy Table-----------------------------------
Wall time: 22min 13s

         DT    SVM    LR    KNN
0      0.49   0.77  0.77   0.62
1      0.49   0.67  0.77   0.56
2      0.92   0.85  0.87   0.82
3      0.55   0.53  0.66   0.50
4      0.71   0.74  0.68   0.68
mean  0.632  0.712  0.75  0.636

In [21]:
%%time
train_cv,clf_report=kfoldcv(model=densenet121(),epochs=epoch,batchsize=batchsize,data=data,lr=0.001,skip_tuning=False,aug=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Fracture      0.636   0.732     0.678
Normal        0.576   0.434     0.482
macro         0.604   0.580     0.578
weighted      0.614   0.612     0.600
------------------ SVM ----------------
          precision  recall  f1-score
Fracture      0.758   0.724     0.736
Normal        0.648   0.684     0.660
macro         0.702   0.706     0.700
weighted      0.720   0.704     0.708
------------------ logistic regression ----------------
          precision  recall  f1-score
Fracture      0.770   0.724     0.744
Normal        0.650   0.702     0.674
macro         0.710   0.716     0.710
weighted      0.726   0.714     0.716
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Fracture      0.750   0.726     0.732
Normal        0.642   0.672     0.646
macro         0.696   0.698     0.690
weighted      0.712   0.694     0.696
--------------------------Accuracy Table-----------------------------------
Wall time: 21min 54s

         DT    SVM     LR    KNN
0      0.59   0.72   0.72   0.77
1      0.56   0.72   0.69   0.62
2      0.54   0.72   0.74   0.64
3      0.63   0.68   0.74   0.68
4      0.74   0.68   0.68   0.76
mean  0.612  0.704  0.714  0.694