# load data

In [1]:
from glob import glob
import os
images=[]
labels=[]
for folder in os.listdir('../dataset/wrist_xray'):
    for pic in glob('../dataset/wrist_xray/{}/*.jpg'.format(folder)):
        images.append(pic)
        labels.append(folder)

In [2]:
import pandas as pd
data=pd.DataFrame(zip(images,labels),columns=['img','label'])
data.label=data.label.map({'Fracture':0,'Normal':1})
data = data.sample(frac=1).reset_index(drop=True)
data.head()

                                                 img  label
0  ../dataset/wrist_xray/Fracture\1 Male (L View)...      0
1   ../dataset/wrist_xray/Fracture\60 F (L View).jpg      0
2                ../dataset/wrist_xray/Normal\34.jpg      1
3   ../dataset/wrist_xray/Fracture\60 F (A View).jpg      0
4   ../dataset/wrist_xray/Fracture\58 F (L View).jpg      0

# top 5 lightest models in torchvision
1	squeezenet1_1	1235496  
2	shufflenet_v2_x0_5	1366792  
3	mnasnet0_5	2218512  
4	mobilenet_v2	3504872  
5	densenet121	7978856  `

In [3]:
import sys
sys.path.append("../src")

In [4]:
from models.squeezenet import squeezenet1_1
from models.mymodels import mymodel1,mymodel2,mymodel3,mymodel4
from models.shufflenet import shufflenet_v2_x0_5
from models.mnastnet import mnasnet0_5
from models.densenet import densenet121
from models.mobilenet import mobilenet
from cross_vals import kfoldcv

In [5]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)/1e6

d:\tutorials\automl\venv\lib\site-packages\ipykernel\ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [6]:
print('MyNet1 parameters :' ,count_parameters(mymodel1()))
print('MyNet2 parameters :', count_parameters(mymodel2()))
print('MyNet3 parameters :', count_parameters(mymodel3()))
print('MyNet4 parameters :', count_parameters(mymodel4()))

MyNet1 parameters : 1.158232
MyNet2 parameters : 1.158232
MyNet3 parameters : 1.157848
MyNet4 parameters : 1.157848

In [7]:
epoch=32
batchsize=8
lr=0.001

dim='3D' or '2D' for 3D images and 2D iamges
skip_tuning=False, no grid search applied for hyper-parameter tuning, 
aug=1-> pytorch augmentation
aug=0-> no augmentation
aug=2-> albumentation augmentation
aug=3-> rand augmentation

# MyNet

In [8]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel1(),epochs=epoch,batchsize=batchsize,data=data,\
                            lr=lr,skip_tuning=True,aug=1,dim='2D',pca=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors','autoML']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.654   0.664     0.642
Class 1       0.550   0.534     0.520
macro         0.604   0.600     0.580
weighted      0.634   0.592     0.594
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.754   0.758     0.752
Class 1       0.666   0.668     0.658
macro         0.712   0.712     0.708
weighted      0.738   0.722     0.724
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.736   0.728     0.724
Class 1       0.626   0.638     0.618
macro         0.684   0.684     0.670
weighted      0.714   0.684     0.688
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.734   0.736     0.726
Class 1       0.634   0.646     0.628
macro         0.682   0.690     0.676
weighted      0.712   0.692     0.692
------------------ autoML ----------------
          precision  recall  f1-score
Class 0       0.810   0.782     0.792
Class 1       0.704   0.736     0.716
macro         0.756   0.758     0.752
weighted      0.780   0.772     0.770
--------------------------Accuracy Table-----------------------------------
Wall time: 16min 12s

         DT    SVM     LR    KNN     ML
0      0.46   0.67   0.62   0.67   0.74
1      0.54   0.72   0.79   0.62   0.74
2      0.64   0.67   0.59   0.64   0.77
3      0.61   0.76   0.71   0.79   0.82
4      0.71   0.79   0.71   0.74   0.79
mean  0.592  0.722  0.684  0.692  0.772

In [9]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel2(),epochs=epoch,batchsize=batchsize,data=data,\
                            lr=lr,skip_tuning=True,aug=1,dim='2D',pca=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors','autoML']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.750   0.782     0.756
Class 1       0.676   0.652     0.650
macro         0.712   0.716     0.702
weighted      0.744   0.716     0.718
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.854   0.778     0.806
Class 1       0.738   0.826     0.762
macro         0.794   0.800     0.784
weighted      0.822   0.792     0.796
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.808   0.768     0.784
Class 1       0.696   0.758     0.718
macro         0.752   0.762     0.750
weighted      0.780   0.764     0.766
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.782   0.700     0.728
Class 1       0.644   0.740     0.670
macro         0.710   0.718     0.698
weighted      0.746   0.704     0.712
------------------ autoML ----------------
          precision  recall  f1-score
Class 0       0.900   0.844     0.870
Class 1       0.796   0.880     0.828
macro         0.850   0.862     0.848
weighted      0.872   0.852     0.858
--------------------------Accuracy Table-----------------------------------
Wall time: 14min 52s

         DT    SVM     LR    KNN     ML
0      0.64   0.74   0.72   0.56   0.79
1      0.72   0.74   0.72   0.67   0.79
2      0.69   0.77   0.77   0.74   0.87
3      0.74   0.87   0.79   0.76   0.89
4      0.79   0.84   0.82   0.79   0.92
mean  0.716  0.792  0.764  0.704  0.852

In [10]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel3(),epochs=epoch,batchsize=batchsize,data=data,\
                            lr=lr,skip_tuning=True,aug=1,dim='2D',pca=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors','autoML']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.800   0.866     0.824
Class 1       0.766   0.700     0.708
macro         0.784   0.784     0.768
weighted      0.808   0.786     0.782
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.876   0.912     0.888
Class 1       0.856   0.844     0.838
macro         0.864   0.878     0.864
weighted      0.886   0.870     0.872
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.862   0.844     0.844
Class 1       0.786   0.840     0.792
macro         0.822   0.840     0.816
weighted      0.854   0.824     0.826
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.866   0.892     0.874
Class 1       0.830   0.828     0.818
macro         0.846   0.860     0.848
weighted      0.868   0.856     0.856
------------------ autoML ----------------
          precision  recall  f1-score
Class 0       0.878   0.952     0.912
Class 1       0.910   0.844     0.866
macro         0.892   0.896     0.892
weighted      0.906   0.896     0.898
--------------------------Accuracy Table-----------------------------------
Wall time: 14min 8s

         DT   SVM     LR    KNN     ML
0      0.79  0.85   0.77   0.87   0.92
1      0.82  0.87   0.85   0.85   0.87
2      0.82  0.90   0.82   0.90   0.90
3      0.68  0.84   0.84   0.84   0.87
4      0.82  0.89   0.84   0.82   0.92
mean  0.786  0.87  0.824  0.856  0.896

In [11]:
%%time
train_cv,clf_report=kfoldcv(model=mymodel4(),epochs=epoch,batchsize=batchsize,data=data,\
                            lr=lr,skip_tuning=True,aug=1,dim='2D',pca=False)
for clf in ['Decision Tree','SVM',"logistic regression",'K Nearest neighbors','autoML']:
    print('------------------',clf,'----------------')
    print(clf_report[0][clf][0])
    
print('--------------------------Accuracy Table-----------------------------------')
clf_report[1]

------------------ Decision Tree ----------------
          precision  recall  f1-score
Class 0       0.776   0.832     0.792
Class 1       0.750   0.710     0.714
macro         0.762   0.772     0.754
weighted      0.788   0.764     0.762
------------------ SVM ----------------
          precision  recall  f1-score
Class 0       0.894   0.904     0.898
Class 1       0.858   0.876     0.862
macro         0.876   0.888     0.880
weighted      0.892   0.886     0.888
------------------ logistic regression ----------------
          precision  recall  f1-score
Class 0       0.822   0.784     0.798
Class 1       0.712   0.782     0.738
macro         0.766   0.782     0.770
weighted      0.794   0.778     0.780
------------------ K Nearest neighbors ----------------
          precision  recall  f1-score
Class 0       0.882   0.878     0.876
Class 1       0.834   0.874     0.844
macro         0.856   0.874     0.862
weighted      0.878   0.866     0.868
------------------ autoML ----------------
          precision  recall  f1-score
Class 0       0.922   0.914     0.918
Class 1       0.868   0.906     0.884
macro         0.896   0.910     0.902
weighted      0.914   0.908     0.910
--------------------------Accuracy Table-----------------------------------
Wall time: 14min 12s

         DT    SVM     LR    KNN     ML
0      0.85   0.87   0.77   0.87   0.87
1      0.72   0.79   0.67   0.77   0.85
2      0.67   0.87   0.74   0.85   0.90
3      0.84   0.95   0.84   0.92   0.95
4      0.74   0.95   0.87   0.92   0.97
mean  0.764  0.886  0.778  0.866  0.908